server:
  port: 8080

spring:
  application:
    name: service-provider

eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka

jdbc:
  datasource:
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//localhost:1521/orcl
      username: xiaobai
      publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKd5LQOK81Mq/NFDZYFZcynL/rRHIuIQ+oBVjR0ut7IAfmMoQEMaAi3g2MKEVHWN2dUaQK9O68C1OnVKO0x/W6MCAwEAAQ==
      password: NQZWLdO9qBN2DZAIdIZileCNQx9HHg/Jv1jIdaj47WYex5Xnj/NjZUx/jKFPXJdTVPUAmsONTa3MHcUhK8khVQ==
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j,config
    connectionProperties: config.decrypt=true;config.decrypt.key=${master.publicKey};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
